live_config_reload = true

[window]

opacity = 0.5

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Cascadia Code PL"
bold.family = "Cascadia Code PL"
italic.family = "Cascadia Code PL"
bold_italic.family = "Cascadia Code PL"

size = 15.0

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.
